apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 # Pod 2개 유지
  selector:
    matchLabels: # Pod 관리 식별 기준
      app: nginx # label
  template: # Pod 설계도(라벨, 컨테이너 이미지, 포드 등)
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
