apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # deployment와 같은 label
  ports:
    - protocol: TCP
      port: 80 # 서비스 자체 포트
      targetPort: 80 # 트래픽 전달 포트
      nodePort: 30080 # 외부 접근 포트(30000~32767)
  type: NodePort # node ip
