sonar.projectKey=gbsw-cs_cs_backend
sonar.organization=gbsw-cs
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,node_modules/**,dist/**
sonar.host.url=https://sonarcloud.io